import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Acterio Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background overflow-y-auto my_scoll scroll-smooth">{children}</body>
    </html>
  );
}
